### ISSUE TITLE
TwitterKoreanProcessorJava.java#L94

### ISSUE THREAD

**Issue by ZheyuJin** [twitter/twitter-korean-text#52]
TwitterKoreanProcessorJava.java#L94 : this line is returning something in Scala world, and when iterating over the result in Java it's unbearably slow. Is there a way to make the iteration over tokenizeToStrings(CharSequence text)'s result faster in Java?

Maybe this is not a problem for Scala users, but it is a problem for Java users..

**Comment by nlpenguin** [comment]
Hi,

Sorry for the late response. I'm travelling in Korea now so only have
limited availability.

It seems this problem is related to this:
https://issues.scala-lang.org/browse/SI-4077, which should have been fixed
as we're using the latest Scala version.

You can re-implement the conversion directly iterating the Scala list. I
will try to work on it when I get back to SF.


Thanks, please let me know if you need further information.

**Comment by nlpenguin** [comment]
This was address by 4.0 release.
